VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sayfa4"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

Private Sub ToggleButton2_Click()
 UserForm2.Show
End Sub

Private Sub ToggleButton3_Click()
UserForm3.Show
End Sub

Private Sub ToggleButton4_Click()
UserForm1.Show
End Sub

Private Sub ToggleButton5_Click()
UserForm4.Show
End Sub

Private Sub ToggleButton6_Click()
UserForm5.Show
End Sub

Private Sub ToggleButton7_Click()
UserForm7.Show
End Sub

Private Sub ToggleButton8_Click()
UserForm6.Show
End Sub

